name: build

on:
  workflow_dispatch:
  push:
      branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  DOTNET_NOLOGO: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --configuration Release 
          /p:CollectCoverage=true 
          /p:CoverletOutputFormat="\"cobertura,json\""
          /p:CoverletOutput=../coverage/
          /p:IncludeTestAssembly=false 
          /p:MergeWith=../coverage/coverage.json
          /maxcpucount:1 -m:1
      - name: Upload dotnet test results
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Sidio.Web.Security/Sidio.Web.Security/src/coverage/coverage.json
          format: cobertura
        if: ${{ always() }}
