name: build

on:
  workflow_dispatch:
  push:
      branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  actions: read
  id-token: write

env:
  DOTNET_NOLOGO: true

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4 #sonar scanner requires jdk
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Setup dotnet 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Setup dotnet 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Install dotnet-sonarscanner
        run: dotnet tool install --global dotnet-sonarscanner
      - name: install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage
      - name: Install dependencies
        run: dotnet restore
      - name: dotnet build,test and sonar analyze
        run: |
          dotnet sonarscanner begin \
          -k:"marthijn_Sidio.Web.Security" \
          -o:"marthijn" \
          -d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          -d:sonar.host.url="https://sonarcloud.io/" \
          -d:sonar.exclusions=".github/**" \
          -d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --configuration Release
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          dotnet sonarscanner end -d:sonar.token="${{ secrets.SONAR_TOKEN }}"
